// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "taskforge/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Result
	//	*WorkerMessage_Heartbeat
	Message       isWorkerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetMessage() isWorkerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WorkerMessage) GetHello() *WorkerHello {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetResult() *common.ExecutionResult {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *WorkerHeartbeat {
	if x != nil {
		if x, ok := x.Message.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isWorkerMessage_Message interface {
	isWorkerMessage_Message()
}

type WorkerMessage_Hello struct {
	Hello *WorkerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Result struct {
	Result *common.ExecutionResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *WorkerHeartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Message() {}

func (*WorkerMessage_Result) isWorkerMessage_Message() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Message() {}

type WorkerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHello) Reset() {
	*x = WorkerHello{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHello) ProtoMessage() {}

func (x *WorkerHello) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHello.ProtoReflect.Descriptor instead.
func (*WorkerHello) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerHello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type WorkerHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RunningTasks  int32                  `protobuf:"varint,2,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHeartbeat) Reset() {
	*x = WorkerHeartbeat{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeat) ProtoMessage() {}

func (x *WorkerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeat.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeat) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerHeartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHeartbeat) GetRunningTasks() int32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

type SchedulerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*SchedulerMessage_Execute
	Message       isSchedulerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerMessage) Reset() {
	*x = SchedulerMessage{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerMessage) ProtoMessage() {}

func (x *SchedulerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerMessage.ProtoReflect.Descriptor instead.
func (*SchedulerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *SchedulerMessage) GetMessage() isSchedulerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SchedulerMessage) GetExecute() *common.ExecutionRequest {
	if x != nil {
		if x, ok := x.Message.(*SchedulerMessage_Execute); ok {
			return x.Execute
		}
	}
	return nil
}

type isSchedulerMessage_Message interface {
	isSchedulerMessage_Message()
}

type SchedulerMessage_Execute struct {
	Execute *common.ExecutionRequest `protobuf:"bytes,1,opt,name=execute,proto3,oneof"`
}

func (*SchedulerMessage_Execute) isSchedulerMessage_Message() {}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x06worker\x1a\fcommon.proto\"\xb3\x01\n" +
	"\rWorkerMessage\x12+\n" +
	"\x05hello\x18\x01 \x01(\v2\x13.worker.WorkerHelloH\x00R\x05hello\x121\n" +
	"\x06result\x18\x02 \x01(\v2\x17.common.ExecutionResultH\x00R\x06result\x127\n" +
	"\theartbeat\x18\x03 \x01(\v2\x17.worker.WorkerHeartbeatH\x00R\theartbeatB\t\n" +
	"\amessage\"*\n" +
	"\vWorkerHello\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"S\n" +
	"\x0fWorkerHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12#\n" +
	"\rrunning_tasks\x18\x02 \x01(\x05R\frunningTasks\"S\n" +
	"\x10SchedulerMessage\x124\n" +
	"\aexecute\x18\x01 \x01(\v2\x18.common.ExecutionRequestH\x00R\aexecuteB\t\n" +
	"\amessage2T\n" +
	"\rWorkerService\x12C\n" +
	"\fWorkerStream\x12\x15.worker.WorkerMessage\x1a\x18.worker.SchedulerMessage(\x010\x01B\x18Z\x16taskforge/proto/workerb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_worker_proto_goTypes = []any{
	(*WorkerMessage)(nil),           // 0: worker.WorkerMessage
	(*WorkerHello)(nil),             // 1: worker.WorkerHello
	(*WorkerHeartbeat)(nil),         // 2: worker.WorkerHeartbeat
	(*SchedulerMessage)(nil),        // 3: worker.SchedulerMessage
	(*common.ExecutionResult)(nil),  // 4: common.ExecutionResult
	(*common.ExecutionRequest)(nil), // 5: common.ExecutionRequest
}
var file_worker_proto_depIdxs = []int32{
	1, // 0: worker.WorkerMessage.hello:type_name -> worker.WorkerHello
	4, // 1: worker.WorkerMessage.result:type_name -> common.ExecutionResult
	2, // 2: worker.WorkerMessage.heartbeat:type_name -> worker.WorkerHeartbeat
	5, // 3: worker.SchedulerMessage.execute:type_name -> common.ExecutionRequest
	0, // 4: worker.WorkerService.WorkerStream:input_type -> worker.WorkerMessage
	3, // 5: worker.WorkerService.WorkerStream:output_type -> worker.SchedulerMessage
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Result)(nil),
		(*WorkerMessage_Heartbeat)(nil),
	}
	file_worker_proto_msgTypes[3].OneofWrappers = []any{
		(*SchedulerMessage_Execute)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
