// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: scheduler.proto

package scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	_ "taskforge/proto/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // "go"
	Code          []byte                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFunctionRequest) Reset() {
	*x = RegisterFunctionRequest{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFunctionRequest) ProtoMessage() {}

func (x *RegisterFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFunctionRequest.ProtoReflect.Descriptor instead.
func (*RegisterFunctionRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterFunctionRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RegisterFunctionRequest) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

type RegisterFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFunctionResponse) Reset() {
	*x = RegisterFunctionResponse{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFunctionResponse) ProtoMessage() {}

func (x *RegisterFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFunctionResponse.ProtoReflect.Descriptor instead.
func (*RegisterFunctionResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterFunctionResponse) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

type TriggerExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerExecutionRequest) Reset() {
	*x = TriggerExecutionRequest{}
	mi := &file_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerExecutionRequest) ProtoMessage() {}

func (x *TriggerExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerExecutionRequest.ProtoReflect.Descriptor instead.
func (*TriggerExecutionRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerExecutionRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *TriggerExecutionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TriggerExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // ACCEPTED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerExecutionResponse) Reset() {
	*x = TriggerExecutionResponse{}
	mi := &file_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerExecutionResponse) ProtoMessage() {}

func (x *TriggerExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerExecutionResponse.ProtoReflect.Descriptor instead.
func (*TriggerExecutionResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerExecutionResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *TriggerExecutionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetExecutionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusRequest) Reset() {
	*x = GetExecutionStatusRequest{}
	mi := &file_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusRequest) ProtoMessage() {}

func (x *GetExecutionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *GetExecutionStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetExecutionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // PENDING | RUNNING | COMPLETED | FAILED
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusResponse) Reset() {
	*x = GetExecutionStatusResponse{}
	mi := &file_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusResponse) ProtoMessage() {}

func (x *GetExecutionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *GetExecutionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetExecutionStatusResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *GetExecutionStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\tscheduler\x1a\fcommon.proto\"]\n" +
	"\x17RegisterFunctionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\fR\x04code\";\n" +
	"\x18RegisterFunctionResponse\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\"T\n" +
	"\x17TriggerExecutionRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"U\n" +
	"\x18TriggerExecutionResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\">\n" +
	"\x19GetExecutionStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"b\n" +
	"\x1aGetExecutionStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xaf\x02\n" +
	"\x10SchedulerService\x12[\n" +
	"\x10RegisterFunction\x12\".scheduler.RegisterFunctionRequest\x1a#.scheduler.RegisterFunctionResponse\x12[\n" +
	"\x10TriggerExecution\x12\".scheduler.TriggerExecutionRequest\x1a#.scheduler.TriggerExecutionResponse\x12a\n" +
	"\x12GetExecutionStatus\x12$.scheduler.GetExecutionStatusRequest\x1a%.scheduler.GetExecutionStatusResponseB\x1bZ\x19taskforge/proto/schedulerb\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_scheduler_proto_goTypes = []any{
	(*RegisterFunctionRequest)(nil),    // 0: scheduler.RegisterFunctionRequest
	(*RegisterFunctionResponse)(nil),   // 1: scheduler.RegisterFunctionResponse
	(*TriggerExecutionRequest)(nil),    // 2: scheduler.TriggerExecutionRequest
	(*TriggerExecutionResponse)(nil),   // 3: scheduler.TriggerExecutionResponse
	(*GetExecutionStatusRequest)(nil),  // 4: scheduler.GetExecutionStatusRequest
	(*GetExecutionStatusResponse)(nil), // 5: scheduler.GetExecutionStatusResponse
}
var file_scheduler_proto_depIdxs = []int32{
	0, // 0: scheduler.SchedulerService.RegisterFunction:input_type -> scheduler.RegisterFunctionRequest
	2, // 1: scheduler.SchedulerService.TriggerExecution:input_type -> scheduler.TriggerExecutionRequest
	4, // 2: scheduler.SchedulerService.GetExecutionStatus:input_type -> scheduler.GetExecutionStatusRequest
	1, // 3: scheduler.SchedulerService.RegisterFunction:output_type -> scheduler.RegisterFunctionResponse
	3, // 4: scheduler.SchedulerService.TriggerExecution:output_type -> scheduler.TriggerExecutionResponse
	5, // 5: scheduler.SchedulerService.GetExecutionStatus:output_type -> scheduler.GetExecutionStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
